import Head from 'next/head'
import Section from '../components/Section'
import Main from '../components/Main'
import Navbar from '../components/Navbar/index'
import Tech from '../components/Tech/index'

export default function Home() {
  return (
    <div>
      <Head>
        <title>giilen.mn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/giilen.png" />
      </Head>
      <Navbar/>
      <Section/>
      <Main/>
      <Tech/>
    </div>
  )
}