import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>giilen.mn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/giilen.png" />
      </Head>
      <div>
        Hello my giilen.mn welcome
      </div>
      <h1>my new bisuness</h1>
    </div>
  )
}